name: img

on:
  push:

jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout img
      run: sh clone-img.sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
    - name: Build
      run: |
        docker build -f img/Dockerfile .