name: img

on:
  push:
    branches:
    - main
    paths:
    - "img.yaml"
    - "IMG_VERSION.txt"

jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout img
      run: sh clone-img.sh
    - name: Set img version
      id: img-version
      run: echo "::set-output name=img_version::$(cat IMG_VERSION.txt)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64,linux/amd64,linux/arm
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
        version: latest
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: img
        file: img/Dockerfile
        platforms: ${{ steps.buildx.outputs.platforms }}
        tags: |
          steven0351/img:latest
          steven0351/img:${{ steps.img-version.outputs.img_version }}